#!/usr/bin/env python3
"""Keep every client manifest in sync with the package's single source of truth.

Source of truth: ./plugin.json — the Agent Plugins 1.0 portable manifest at the
package root. Identity (name, version, description, author, repository, license)
is read from there and never re-typed in a client adapter.

Generated files (never edit these by hand — run this script instead):

  .claude-plugin/plugin.json                       Claude Code plugin manifest
  .claude-plugin/marketplace.json                  Claude Code marketplace, also consumed by
                                                   VS Code via chat.plugins.marketplaces
  .github/plugin/marketplace.json                  GitHub Copilot CLI marketplace
  .agents/plugins/marketplace.json                 Codex CLI repo marketplace
  .agents/plugins/editorial-recension/plugin.json  Google Antigravity workspace plugin marker
  .agents/plugins/editorial-recension/skills       symlink -> ../../../skills

Propagation contract: the six identity keys above travel to the client manifests;
root-only keys (`keywords`, `extensions`) stay in the portable manifest. Codex
presentation data is *read* from `extensions["com.openai"]["interface"]` (with a
fallback to the flat `extensions["com.openai"]` shape) for the marketplace label.

Modes:

  (no flags)    drift check + tree surface + structural validation; exit 1 on any problem
  --write       rewrite every generated file from the source of truth, then re-check
  --check       drift check + tree surface only
  --validate    structural validation only

The default mode and `--check` guard the tree (generated bytes, file types,
generator-owned directories, client-visible artefacts); `--validate` guards each
manifest's fields. CI runs both.

The drift check compares bytes on disk with generated bytes, so CRLF edits,
reformatting, key reordering and extra keys all fail; it also requires every
generated path to be a regular file (never a symlink), every generator-owned
directory to hold exactly the entries this script emits, and no hooks/MCP/command/
rule artefact to appear at the package root unnoticed. CI runs this script on every
push and pull request and re-runs `--write`, failing on any working-tree change,
tracked or not.

Standard library only, no network, no writes unless --write is passed.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from typing import NoReturn

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# Content that is not part of the portable manifest, kept in exactly one place.
# ---------------------------------------------------------------------------

# Marketplace listing copy. Rewritten into every marketplace file.
BLURB = (
    "Two-agent editing loop: an editor applies five named schemata, an evaluator "
    "scores blind before reading the editor's trace, and they loop until the text passes."
)

# Codex marketplace entry category, used only when the manifest carries none.
CODEX_CATEGORY = "Writing"

# Codex marketplace source: object form, as the OpenAI packaging docs specify
# ("Always include policy.installation, policy.authentication, and category").
CODEX_SOURCE_OBJECT = {"source": "local", "path": "./"}
CODEX_POLICY = {"installation": "AVAILABLE", "authentication": "ON_INSTALL"}

# Claude/Copilot marketplace source: path relative to the marketplace root.
MARKETPLACE_SOURCE_PATH = "./"

# Google Antigravity plugin marker schema (antigravity.google/docs/cli/plugins/).
# The vendor schema lists only name + description under additionalProperties:false,
# while the vendor's own manifest example ships $schema — we follow the example.
ANTIGRAVITY_SCHEMA = "https://antigravity.google/schemas/v1/plugin.json"

ANTIGRAVITY_DIR = ".agents/plugins/editorial-recension"
ANTIGRAVITY_SKILLS_LINK = "skills"
ANTIGRAVITY_SKILLS_TARGET = "../../../skills"

# Directories this script owns. Any other entry inside them is drift by definition.
GENERATED_DIRS = {
    ".claude-plugin": ("plugin.json", "marketplace.json"),
    ".github/plugin": ("marketplace.json",),
    ".agents/plugins": ("marketplace.json", "editorial-recension"),
}

# Client-visible artefacts that must never appear at the package root unnoticed:
# hooks, MCP servers, commands and rules execute or load on the user's machine, and
# they are not part of this package's contract. A deliberate addition belongs in a
# reviewed PR that also updates this list.
FORBIDDEN_ROOT_ARTEFACTS = (
    "hooks",
    "hooks.json",
    "mcp.json",
    ".mcp.json",
    "commands",
    "rules",
    ".codex-plugin",
    ".cursor-plugin",
    ".plugin",
    "openclaw.plugin.json",
    ".claude",
)

KEBAB = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
ANTIGRAVITY_NAME = re.compile(r"[a-zA-Z0-9-_]+")


class GuardInputError(Exception):
    """Raised for malformed repository state; reported as a message, never a traceback."""


def guard_fail(message: str) -> NoReturn:
    raise SystemExit(f"manifest guard: {message}")


# ---------------------------------------------------------------------------
# Source of truth
# ---------------------------------------------------------------------------


def read_json_object(path: str, label: str) -> dict:
    if os.path.islink(path):
        guard_fail(f"{label}: is a symlink, expected a regular file")
    if os.path.isdir(path):
        guard_fail(f"{label}: is a directory, expected a regular file")
    if not os.path.exists(path):
        guard_fail(f"{label}: not found")
    try:
        with open(path, "rb") as fh:
            data = json.loads(fh.read().decode("utf-8"))
    except UnicodeDecodeError as exc:
        guard_fail(f"{label}: not valid UTF-8 ({exc})")
    except json.JSONDecodeError as exc:
        guard_fail(f"{label}: invalid JSON ({exc})")
    except OSError as exc:
        guard_fail(f"{label}: cannot read ({exc})")
    if not isinstance(data, dict):
        guard_fail(f"{label}: top level must be a JSON object, found {type(data).__name__}")
    return data


def non_empty_str(obj: dict, key: str, label: str) -> str:
    value = obj.get(key)
    if not isinstance(value, str) or not value.strip():
        guard_fail(f"{label}: {key} must be a non-empty string, found {value!r}")
    return value


def read_source(repo_root: str) -> dict:
    plugin = read_json_object(os.path.join(repo_root, "plugin.json"), "plugin.json")
    non_empty_str(plugin, "name", "plugin.json")
    non_empty_str(plugin, "version", "plugin.json")
    non_empty_str(plugin, "description", "plugin.json")
    if not KEBAB.fullmatch(plugin["name"]):
        guard_fail(f"plugin.json: name {plugin['name']!r} must be kebab-case")
    author = plugin.get("author")
    if author is not None:
        if not isinstance(author, dict):
            guard_fail(f"plugin.json: author must be an object, found {type(author).__name__}")
        non_empty_str(author, "name", "plugin.json author")
    extensions = plugin.get("extensions")
    if extensions is not None and not isinstance(extensions, dict):
        guard_fail(f"plugin.json: extensions must be an object, found {type(extensions).__name__}")
    return plugin


def codex_display_name(plugin: dict) -> str:
    """Codex presentation label: documented nesting first, flat shape as fallback."""
    openai = (plugin.get("extensions") or {}).get("com.openai") or {}
    if not isinstance(openai, dict):
        guard_fail("plugin.json: extensions['com.openai'] must be an object")
    interface = openai.get("interface")
    if isinstance(interface, dict) and interface.get("displayName"):
        return str(interface["displayName"])
    return str(openai.get("displayName") or plugin["name"])


def codex_category(plugin: dict) -> str:
    """Codex marketplace entry category, taken from the manifest when present."""
    openai = (plugin.get("extensions") or {}).get("com.openai") or {}
    if isinstance(openai, dict):
        interface = openai.get("interface")
        if isinstance(interface, dict) and interface.get("category"):
            return str(interface["category"])
        if openai.get("category"):
            return str(openai["category"])
    return CODEX_CATEGORY


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def build_expected(plugin: dict) -> dict[str, str]:
    """Return {relative path: generated text} for every generated manifest."""
    name = plugin["name"]
    version = plugin["version"]
    description = plugin["description"]
    author = plugin.get("author") or {}
    author_name = author.get("name")

    def dump(obj: dict) -> str:
        return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"

    claude_plugin = {
        "name": name,
        "version": version,
        "description": description,
        "author": author,
        "repository": plugin.get("repository"),
        "license": plugin.get("license"),
    }
    claude_plugin = {k: v for k, v in claude_plugin.items() if v is not None}

    claude_marketplace = {
        "name": name,
        "owner": {"name": author_name},
        "metadata": {"description": BLURB, "version": version},
        "plugins": [
            {
                "name": name,
                "source": MARKETPLACE_SOURCE_PATH,
                "description": BLURB,
                "version": version,
            }
        ],
    }

    copilot_marketplace = {
        "name": name,
        "owner": {"name": author_name},
        "metadata": {"description": BLURB, "version": version},
        "plugins": [
            {
                "name": name,
                "description": BLURB,
                "version": version,
                "source": MARKETPLACE_SOURCE_PATH,
            }
        ],
    }

    codex_marketplace = {
        "name": name,
        "interface": {"displayName": codex_display_name(plugin)},
        "plugins": [
            {
                "name": name,
                "source": dict(CODEX_SOURCE_OBJECT),
                "policy": dict(CODEX_POLICY),
                "category": codex_category(plugin),
            }
        ],
    }

    antigravity_plugin = {
        "$schema": ANTIGRAVITY_SCHEMA,
        "name": name,
        "description": BLURB,
    }

    return {
        ".claude-plugin/plugin.json": dump(claude_plugin),
        ".claude-plugin/marketplace.json": dump(claude_marketplace),
        ".github/plugin/marketplace.json": dump(copilot_marketplace),
        ".agents/plugins/marketplace.json": dump(codex_marketplace),
        f"{ANTIGRAVITY_DIR}/plugin.json": dump(antigravity_plugin),
    }


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------


def check_drift(repo_root: str, expected: dict[str, str]) -> list[str]:
    problems: list[str] = []
    for rel, text in sorted(expected.items()):
        path = os.path.join(repo_root, rel)
        if os.path.islink(path):
            problems.append(
                f"{rel}: is a symlink; every generated manifest must be a regular file "
                "(run: python3 scripts/sync_manifests.py --write after removing the link)"
            )
            continue
        if not os.path.isfile(path):
            problems.append(f"{rel}: missing (run: python3 scripts/sync_manifests.py --write)")
            continue
        with open(path, "rb") as fh:
            actual = fh.read()
        if actual != text.encode("utf-8"):
            problems.append(f"{rel}: drifted from plugin.json (run: python3 scripts/sync_manifests.py --write)")

    link_path = os.path.join(repo_root, ANTIGRAVITY_DIR, ANTIGRAVITY_SKILLS_LINK)
    if not os.path.islink(link_path):
        problems.append(
            f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK}: not a symlink to {ANTIGRAVITY_SKILLS_TARGET} "
            "(run: python3 scripts/sync_manifests.py --write; on Windows, enable core.symlinks)"
        )
    elif os.readlink(link_path) != ANTIGRAVITY_SKILLS_TARGET:
        problems.append(
            f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK}: points at {os.readlink(link_path)}, "
            f"expected {ANTIGRAVITY_SKILLS_TARGET}"
        )
    elif not os.path.isdir(link_path):
        problems.append(
            f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK}: dangling link (target {ANTIGRAVITY_SKILLS_TARGET} missing)"
        )
    return problems


def check_surface(repo_root: str) -> list[str]:
    """Nothing client-visible may appear outside the set this generator owns."""
    problems: list[str] = []
    for entry in FORBIDDEN_ROOT_ARTEFACTS:
        if os.path.lexists(os.path.join(repo_root, entry)):
            problems.append(
                f"{entry}: client-visible artefact outside the generated manifest set "
                "(hooks/MCP/commands/rules are not part of this package; if the addition is "
                "deliberate, ship it in a reviewed PR that updates FORBIDDEN_ROOT_ARTEFACTS)"
            )
    for rel, allowed in sorted(GENERATED_DIRS.items()):
        directory = os.path.join(repo_root, rel)
        if not os.path.isdir(directory):
            problems.append(f"{rel}: missing directory")
            continue
        unexpected = sorted(name for name in os.listdir(directory) if name not in allowed)
        if unexpected:
            problems.append(
                f"{rel}: unexpected entries {unexpected}; the generator owns this directory "
                f"(expected {sorted(allowed)})"
            )
    return problems


def load_json(path: str, rel: str, problems: list[str]) -> dict | None:
    if not os.path.exists(path):
        problems.append(f"{rel}: missing")
        return None
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
    except json.JSONDecodeError as exc:
        problems.append(f"{rel}: invalid JSON ({exc})")
        return None
    if not isinstance(data, dict):
        problems.append(f"{rel}: top level must be a JSON object, found {type(data).__name__}")
        return None
    return data


def require_str(obj: dict, key: str, label: str, problems: list[str]) -> None:
    if not isinstance(obj.get(key), str) or not obj.get(key, "").strip():
        problems.append(f"{label}: {key} must be a non-empty string, found {obj.get(key)!r}")


def require_entries(container, label: str, problems: list[str]) -> list[dict]:
    if not isinstance(container, list) or not container:
        problems.append(f"{label}: must be a non-empty list")
        return []
    entries = []
    for index, entry in enumerate(container):
        if not isinstance(entry, dict):
            problems.append(f"{label}[{index}]: must be an object, found {type(entry).__name__}")
            continue
        entries.append(entry)
    return entries


def resolves_to_plugin(repo_root: str, rel_path: str) -> bool:
    target = os.path.join(repo_root, rel_path)
    return os.path.isfile(os.path.join(target, "plugin.json"))


def validate(repo_root: str, plugin: dict) -> list[str]:
    """Structural checks, one per harness, from the Phase 0 doc table on issue #17."""
    problems: list[str] = []
    name = plugin["name"]
    version = plugin["version"]

    def path_of(rel: str) -> str:
        return os.path.join(repo_root, rel)

    # --- Claude Code plugin manifest -------------------------------------
    rel = ".claude-plugin/plugin.json"
    claude_plugin = load_json(path_of(rel), rel, problems)
    if claude_plugin is not None:
        for key in ("name", "version", "description", "author"):
            if key not in claude_plugin:
                problems.append(f"{rel}: missing required field {key!r}")
        for key in ("name", "version", "description", "repository", "license"):
            if key in claude_plugin:
                require_str(claude_plugin, key, rel, problems)
        if "author" in claude_plugin:
            if not isinstance(claude_plugin["author"], dict):
                problems.append(f"{rel}: author must be an object")
            else:
                require_str(claude_plugin["author"], "name", f"{rel} author", problems)
        if claude_plugin.get("name") != name:
            problems.append(f"{rel}: name {claude_plugin.get('name')!r} != plugin.json {name!r}")
        if claude_plugin.get("version") != version:
            problems.append(f"{rel}: version {claude_plugin.get('version')!r} != plugin.json {version!r}")

    # --- Claude + Copilot marketplaces -----------------------------------
    for rel in (".claude-plugin/marketplace.json", ".github/plugin/marketplace.json"):
        market = load_json(path_of(rel), rel, problems)
        if market is None:
            continue
        require_str(market, "name", rel, problems)
        if isinstance(market.get("name"), str) and not KEBAB.fullmatch(market["name"]):
            problems.append(f"{rel}: marketplace name {market['name']!r} is not kebab-case")
        owner = market.get("owner")
        if not isinstance(owner, dict):
            problems.append(f"{rel}: owner must be an object with a name (required by the Claude/Copilot schemas)")
        else:
            require_str(owner, "name", f"{rel} owner", problems)
        metadata = market.get("metadata")
        if metadata is not None:
            if not isinstance(metadata, dict):
                problems.append(f"{rel}: metadata must be an object")
            else:
                require_str(metadata, "description", f"{rel} metadata", problems)
                if metadata.get("version") != version:
                    problems.append(
                        f"{rel}: metadata.version {metadata.get('version')!r} != plugin.json {version!r}"
                    )
        for entry in require_entries(market.get("plugins"), f"{rel} plugins", problems):
            require_str(entry, "name", f"{rel} plugins[]", problems)
            if entry.get("name") != name:
                problems.append(f"{rel}: entry name {entry.get('name')!r} != plugin.json {name!r}")
            if entry.get("version") != version:
                problems.append(f"{rel}: entry version {entry.get('version')!r} != plugin.json {version!r}")
            source = entry.get("source")
            if not isinstance(source, str):
                problems.append(
                    f"{rel}: plugins[].source must be a relative path string here "
                    "(this project points every client at the package root)"
                )
            elif not resolves_to_plugin(repo_root, source):
                problems.append(f"{rel}: source {source!r} does not resolve to a plugin (no plugin.json)")

    # --- Codex marketplace ----------------------------------------------
    rel = ".agents/plugins/marketplace.json"
    codex = load_json(path_of(rel), rel, problems)
    if codex is not None:
        require_str(codex, "name", rel, problems)
        interface = codex.get("interface")
        if not isinstance(interface, dict):
            problems.append(f"{rel}: interface must be an object")
        else:
            require_str(interface, "displayName", f"{rel} interface", problems)
        for entry in require_entries(codex.get("plugins"), f"{rel} plugins", problems):
            label = f"{rel} plugins[]"
            require_str(entry, "name", label, problems)
            require_str(entry, "category", label, problems)
            source = entry.get("source")
            if (
                not isinstance(source, dict)
                or source.get("source") != "local"
                or not isinstance(source.get("path"), str)
                or not source["path"].startswith("./")
            ):
                problems.append(f"{label}: source must be {{'source': 'local', 'path': './...'}}")
            elif not resolves_to_plugin(repo_root, source["path"]):
                problems.append(f"{label}: path {source['path']!r} does not resolve to a plugin (no plugin.json)")
            policy = entry.get("policy")
            if not isinstance(policy, dict):
                problems.append(f"{label}: policy must be an object")
            else:
                if policy.get("installation") not in ("AVAILABLE", "INSTALLED_BY_DEFAULT", "NOT_AVAILABLE"):
                    problems.append(
                        f"{label}: policy.installation must be one of "
                        "AVAILABLE/INSTALLED_BY_DEFAULT/NOT_AVAILABLE"
                    )
                require_str(policy, "authentication", f"{label} policy", problems)

    # --- Antigravity workspace plugin ------------------------------------
    rel = f"{ANTIGRAVITY_DIR}/plugin.json"
    anti = load_json(path_of(rel), rel, problems)
    if anti is not None:
        allowed = {"$schema", "name", "description"}
        extra = set(anti) - allowed
        if extra:
            problems.append(
                f"{rel}: unsupported keys {sorted(extra)} "
                "(the Antigravity CLI schema sets additionalProperties: false)"
            )
        if anti.get("$schema") != ANTIGRAVITY_SCHEMA:
            problems.append(f"{rel}: $schema must be {ANTIGRAVITY_SCHEMA}")
        require_str(anti, "description", rel, problems)
        if not isinstance(anti.get("name"), str) or not ANTIGRAVITY_NAME.fullmatch(anti.get("name", "")):
            problems.append(f"{rel}: name must match ^[a-zA-Z0-9-_]+$")
        elif anti.get("name") != name:
            problems.append(f"{rel}: name {anti.get('name')!r} != plugin.json {name!r}")

        link = path_of(f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK}")
        if not os.path.isdir(link):
            problems.append(f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK}: does not resolve to a directory")
        elif not os.path.isfile(os.path.join(link, name, "SKILL.md")):
            problems.append(f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK}: missing {name}/SKILL.md")

        entries = sorted(os.listdir(path_of(ANTIGRAVITY_DIR)))
        if entries != sorted(["plugin.json", ANTIGRAVITY_SKILLS_LINK]):
            problems.append(
                f"{ANTIGRAVITY_DIR}: expected exactly plugin.json + {ANTIGRAVITY_SKILLS_LINK}, found {entries}"
            )

    return problems


# ---------------------------------------------------------------------------
# Write mode
# ---------------------------------------------------------------------------


def write_all(repo_root: str, expected: dict[str, str]) -> list[str]:
    written: list[str] = []
    for rel, text in sorted(expected.items()):
        path = os.path.join(repo_root, rel)
        if os.path.islink(path):
            guard_fail(
                f"{rel}: is a symlink and is never written through "
                "(remove it first; on Windows, clone with core.symlinks enabled)"
            )
        if os.path.isdir(path):
            guard_fail(f"{rel}: is a directory, expected a regular file")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        payload = text.encode("utf-8")
        if os.path.isfile(path):
            with open(path, "rb") as fh:
                if fh.read() == payload:
                    continue
        with open(path, "wb") as fh:
            fh.write(payload)
        written.append(rel)

    link_dir = os.path.join(repo_root, ANTIGRAVITY_DIR)
    link_path = os.path.join(link_dir, ANTIGRAVITY_SKILLS_LINK)
    os.makedirs(link_dir, exist_ok=True)
    if os.path.islink(link_path):
        if os.readlink(link_path) != ANTIGRAVITY_SKILLS_TARGET:
            os.remove(link_path)
    if not os.path.islink(link_path):
        if os.path.lexists(link_path):
            guard_fail(
                f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK}: exists and is not a symlink; refusing to "
                "overwrite. On Windows, clone with core.symlinks enabled."
            )
        try:
            os.symlink(ANTIGRAVITY_SKILLS_TARGET, link_path)
        except OSError as exc:
            guard_fail(
                f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK}: cannot create symlink ({exc}); "
                "on Windows, developer mode or core.symlinks is required"
            )
        written.append(f"{ANTIGRAVITY_DIR}/{ANTIGRAVITY_SKILLS_LINK} (symlink)")
    return written


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def run(args: argparse.Namespace) -> int:
    repo_root = os.path.abspath(args.repo_root)
    if not os.path.isdir(repo_root):
        guard_fail(f"--repo-root {repo_root}: not a directory")

    plugin = read_source(repo_root)
    expected = build_expected(plugin)

    if args.write:
        written = write_all(repo_root, expected)
        print("wrote " + ", ".join(written) if written else "nothing to write; all manifests already in sync")
        problems = check_drift(repo_root, expected) + check_surface(repo_root) + validate(repo_root, plugin)
        if problems:
            print(f"manifest guard: {len(problems)} problem(s) remain after writing")
            for problem in problems:
                print(f"  - {problem}")
            return 1
        return 0

    do_check = args.check or not args.validate
    do_validate = args.validate or not args.check

    problems: list[str] = []
    if do_check:
        problems += check_drift(repo_root, expected)
        problems += check_surface(repo_root)
    if do_validate:
        problems += validate(repo_root, plugin)

    if problems:
        print(f"manifest guard: {len(problems)} problem(s)")
        for problem in problems:
            print(f"  - {problem}")
        return 1

    print(f"manifest guard: OK ({len(expected)} generated file(s) in sync with plugin.json {plugin['version']})")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync and verify client manifests against plugin.json")
    parser.add_argument("--write", action="store_true", help="rewrite generated files from plugin.json")
    parser.add_argument("--check", action="store_true", help="drift check only")
    parser.add_argument("--validate", action="store_true", help="structural validation only")
    parser.add_argument("--repo-root", default=REPO_ROOT)
    args = parser.parse_args()

    if args.write and (args.check or args.validate):
        parser.error("--write cannot be combined with --check/--validate: --write already re-checks after writing")

    try:
        return run(args)
    except GuardInputError as exc:
        print(f"manifest guard: {exc}")
        return 2
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, AttributeError, TypeError, KeyError, ValueError) as exc:
        # Malformed repository state must read as a guard message, never a traceback.
        print(f"manifest guard: unexpected input ({type(exc).__name__}: {exc})")
        return 2


if __name__ == "__main__":
    sys.exit(main())